mysqlImage: mysql
mysqlTag: 8.0.28
mongoImage: mongo
mongoTag: 5.0.6-focal
plannerImage: codeurjc/planner
plannerTag: v1.0
rabbitmqImage: rabbitmq
rabbitmqTag: 3.9-management
serverImage: codeurjc/server
serverTag: v1.0
topoServiceImage: codeurjc/toposervice
topoServiceTag: v1.0
weathServiceImage: codeurjc/weatherservice
weathServiceTag: v1.0
nameOverride: ""
fullnameOverride: ""


#release configurations
persistanceEnabled: true
ingressEnabled: true
networkPoliciesEnabled: true
serviceType: NodePort

mysql:
  type: ClusterIP
  mysqlRootPassword: password
  mysqlRootUser: root
  mysqlDatabase: eoloplantsDB
  port: 3306
  mountPath: /var/lib/mysql
  storageClass: mysql


mongodb:
  type: ClusterIP
  database: topoDB
  rootUsername: root
  rootPassword: password
  authenticationDatabase: admin
  port1: 27017
  port2: 27018
  port3: 27019
  mountPath: /data/db
  storageClass: mongodb

rabbitmq:
  type: ClusterIP
  app: rabbitmq
  port1: 5672
  port2: 15672
  rabbitmqDefaultUser: root
  rabbitmqDefaultPass: password
  mountPath: /var/lib/rabbitmq/mnesia
  storageClass: rabbit

weatherservice:
  type: ClusterIP
  port: 9090
  user: 1001

toposervice:
  type: ClusterIP
  user: 1001
  port: 8181

planner:
  user: 1001
  port: 8080

eoloServer:
  user: 1001
  port: 3000
  replicas: 1

ingress:
  host: cluster-ip
  noIngressType: NodePort

replicaCount: 1
