---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "planner.app" . }}-deploy
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ include "planner.app" . }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ include "planner.app" . }}
        dns-policy: enabled
    spec:
      securityContext:
        runAsUser: {{ .Values.planner.user }}
      restartPolicy: Always
      containers:
      - name: {{ include "planner.app" . }}
        image: codeurjc/planner:v1.0
        env:
        - name: TOPO_HOST
          value: {{ include "toposervice.app" . }}-service
        - name: TOPO_PORT
          value: {{ .Values.toposervice.port | quote }}
        - name: GRPC_CLIENT_WEATHERSERVER_ADDRESS
          value: "static://{{ include "weatherservice.app" . }}-service:{{ .Values.weatherservice.port }}"
        - name: SPRING_CLOUD_STREAM_RABBIT_BINDER_NODES
          value: {{ include "rabbitmq.app" . }}-service:5672
        - name: SPRING_RABBITMQ_HOST
          value: {{ include "rabbitmq.app" . }}-service
        - name: SPRING_RABBITMQ_PORT
          value: {{ .Values.rabbitmq.port1 | quote }}
        - name: SPRING_RABBITMQ_USERNAME
          value: {{ .Values.rabbitmq.rabbitmqDefaultUser }}
        - name: SPRING_RABBITMQ_PASSWORD
          value: {{ .Values.rabbitmq.rabbitmqDefaultPass }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "planner.app" . }}-to-{{ include "rabbitmq.app" . }}-{{ include "weatherservice.app" . }}-{{ include "toposervice.app" . }}
spec:
  podSelector:
    matchLabels:
      app: {{ include "planner.app" . }}
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: {{ include "rabbitmq.app" . }}
    ports:
    - port: {{ .Values.rabbitmq.port1 }}
      protocol: TCP
  - to:
    - podSelector:
        matchLabels:
          app: {{ include "weatherservice.app" . }}
    ports:
    - port: {{ .Values.weatherservice.port }}
      protocol: TCP
  - to:
    - podSelector:
        matchLabels:
          app: {{ include "toposervice.app" . }}
    ports:
    - port: {{ .Values.toposervice.port }}
      protocol: TCP
