{{- if .Values.networkPoliciesEnabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-{{ template "deny.fullname" . }}
  labels:
    app: {{ template "deny.name" . }}
    chart: {{ template "deny.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  podSelector:
    matchLabels:
      release: {{ .Release.Name }}
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "dnsegress.fullname" . }}
  labels:
    app: {{ template "dnsegress.name" . }}
    chart: {{ template "dnsegress.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  podSelector:
    matchLabels:
      dns-policy: enabled
      release: {{ .Release.Name }}
  egress:
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
{{- end }}