apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-multi-ingress
  labels:
    app: {{ template "ingress.name" . }}
    chart: {{ template "ingress.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "server.fullname" . }}
                port:
                  number: {{ .Values.eoloServer.port }}
          - path: /toposervice/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "toposervice.fullname" . }}
                port:
                  number: {{ .Values.toposervice.port }}
