apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mongodb.app" . }}-env-config-map
data:
  MONGO_INITDB_DATABASE: {{ .Values.mongodb.database | quote}}
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongodb.rootUsername | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongodb.rootPassword | quote }}

