---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mongodb.fullname" . }}
  labels:
    app: {{ template "mongodb.name" . }}
    chart: {{ template "mongodb.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ include "mongodb.name" . }}
      release: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ include "mongodb.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ include "mongodb.fullname" . }}
        image: "{{ .Values.mongoImage }}:{{ .Values.mongoTag }}"
        envFrom:
          - configMapRef:
              name: {{ include "mongodb.fullname" . }}-env-config-map
        ports:
        - containerPort: {{ .Values.mongodb.port1 }}
        - containerPort: {{ .Values.mongodb.port2 }}
        - containerPort: {{ .Values.mongodb.port3 }}
{{- if .Values.persistanceEnabled }}
        volumeMounts:
        - mountPath: {{ .Values.mongodb.mountPath }}
          name: {{ include "mongodb.fullname" . }}-datadb
      volumes:
      - name: {{ include "mongodb.fullname" . }}-datadb
        persistentVolumeClaim:
          claimName: {{ include "mongodb.fullname" . }}-pvc
{{- end }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "mongodb.fullname" . }}-pv
  labels:
    app: {{ template "mongodb.name" . }}
    chart: {{ template "mongodb.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  storageClassName: {{ .Values.mongodb.storageClass }}
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /db/mongo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mongodb.fullname" . }}-pvc
  labels:
    app: {{ template "mongodb.name" . }}
    chart: {{ template "mongodb.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  storageClassName: {{ .Values.mongodb.storageClass }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi          
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongodb.fullname" . }}
  labels:
    app: {{ template "mongodb.name" . }}
    chart: {{ template "mongodb.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - port: {{ .Values.mongodb.port1 }}
    targetPort: {{ .Values.mongodb.port1 }}
    protocol: TCP
    name: {{ include "mongodb.fullname" . }}-port-27017
  - port: {{ .Values.mongodb.port2 }}
    targetPort: {{ .Values.mongodb.port2 }}
    protocol: TCP
    name: {{ include "mongodb.fullname" . }}-port-27018
  - port: {{ .Values.mongodb.port3 }}
    targetPort: {{ .Values.mongodb.port3 }}
    protocol: TCP
    name: {{ include "mongodb.fullname" . }}-port-27019
  selector:
    app: {{ include "mongodb.name" . }}
    release: {{ .Release.Name }}
  type: {{ .Values.mongodb.type }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "mongodb.fullname" . }}-from-{{ include "toposervice.fullname" . }}
  labels:
    app: {{ template "mongodb.name" . }}
    chart: {{ template "mongodb.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  podSelector:
    matchLabels:
      app: {{ include "mongodb.name" . }}
      release: {{ .Release.Name }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ include "toposervice.name" . }}
          release: {{ .Release.Name }}
    ports:
    - port: {{ .Values.mongodb.port1 }}
      protocol: TCP
