---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "mysql.name" . }}
  labels:
    app: {{ template "mysql.name" . }}
    chart: {{ template "mysql.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ template "mysql.name" . }}
      release: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "mysql.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ include "mysql.name" . }}
        image: "{{ .Values.mysqlImage }}:{{ .Values.mysqlTag }}"
        envFrom:
          - configMapRef:
              name: {{ include "mysql.name" . }}-env-config-map
        ports:
        - containerPort: {{ .Values.mysql.port }}
        volumeMounts:
        - mountPath: {{ .Values.mysql.mountPath }}
          name: {{ include "mysql.name" . }}-datadb
      volumes:
      - name: {{ include "mysql.name" . }}-datadb
        persistentVolumeClaim:
          claimName: {{ include "mysql.name" . }}-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mysql.name" . }}-pvc
  labels:
    app: {{ template "mysql.name" . }}
    chart: {{ template "mysql.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  storageClassName: {{ .Values.mysql.storageClass }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "mysql.name" . }}-pv
  labels:
    type: local
    app: {{ template "mysql.name" . }}
    chart: {{ template "mysql.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  storageClassName: {{ .Values.mysql.storageClass }}
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /db/mysql
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "mysql.name" . }}
  labels:
    app: {{ template "mysql.name" . }}
    chart: {{ template "mysql.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - port: {{ .Values.mysql.port }}
    targetPort: {{ .Values.mysql.port }}
    protocol: TCP
    name: {{ include "mysql.name" . }}-port
  selector:
    app: {{ template "mysql.name" . }}
    release: {{ .Release.Name }}
  type: {{ .Values.mysql.type }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "mysql.name" . }}-from-{{ include "server.name" . }}
  labels:
    app: {{ template "mysql.name" . }}
    chart: {{ template "mysql.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  podSelector:
    matchLabels:
      app: {{ include "mysql.name" . }}
      release: {{ .Release.Name }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ include "server.name" . }}
          release: {{ .Release.Name }}
    ports:
    - port: {{ .Values.mysql.port }}
      protocol: TCP
