apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mysql.app" . }}-env-config-map
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.mysqlRootPassword | quote }}
  MYSQL_DATABASE: {{ .Values.mysql.mysqlDatabase | quote }}
