apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mysql.fullname" . }}-env-config-map
  labels:
    app: {{ template "mysql.name" . }}
    chart: {{ template "mysql.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.mysqlRootPassword | quote }}
  MYSQL_DATABASE: {{ .Values.mysql.mysqlDatabase | quote }}
