---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "planner.fullname" . }}
  labels:
    app: {{ template "planner.name" . }}
    chart: {{ template "planner.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ include "planner.name" . }}
      release: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ include "planner.name" . }}
        release: {{ .Release.Name }}
        dns-policy: enabled
    spec:
      securityContext:
        runAsUser: {{ .Values.planner.user }}
      restartPolicy: Always
      containers:
      - name: {{ include "planner.fullname" . }}
        image: "{{ .Values.plannerImage }}:{{ .Values.plannerTag }}"
        env:
        - name: SERVER_PORT
          value: {{ .Values.planner.port | quote }}
        - name: TOPO_HOST
          value: {{ include "toposervice.fullname" . }}
        - name: TOPO_PORT
          value: "8181"
        - name: GRPC_CLIENT_WEATHERSERVER_ADDRESS
          value: "static://{{ include "weatherservice.fullname" . }}:{{ .Values.weatherservice.port }}"
        - name: SPRING_CLOUD_STREAM_RABBIT_BINDER_NODES
          value: {{ include "rabbitmq.fullname" . }}:5672
        - name: SPRING_RABBITMQ_HOST
          value: {{ include "rabbitmq.fullname" . }}
        - name: SPRING_RABBITMQ_PORT
          value: {{ .Values.rabbitmq.port1 | quote }}
        - name: SPRING_RABBITMQ_USERNAME
          value: {{ .Values.rabbitmq.rabbitmqDefaultUser }}
        - name: SPRING_RABBITMQ_PASSWORD
          value: {{ .Values.rabbitmq.rabbitmqDefaultPass }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "planner.fullname" . }}-to-{{ include "rabbitmq.fullname" . }}-{{ include "weatherservice.fullname" . }}-{{ include "toposervice.fullname" . }}
  labels:
    app: {{ template "server.name" . }}
    chart: {{ template "server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  podSelector:
    matchLabels:
      app: {{ include "planner.name" . }}
      release: {{ .Release.Name }}
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: {{ include "rabbitmq.name" . }}
          release: {{ .Release.Name }}
    ports:
    - port: {{ .Values.rabbitmq.port1 }}
      protocol: TCP
  - to:
    - podSelector:
        matchLabels:
          app: {{ include "weatherservice.name" . }}
          release: {{ .Release.Name }}
    ports:
    - port: {{ .Values.weatherservice.port }}
      protocol: TCP
  - to:
    - podSelector:
        matchLabels:
          app: {{ include "toposervice.name" . }}
          release: {{ .Release.Name }}
    ports:
    - port: {{ .Values.toposervice.port }}
      protocol: TCP