---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  labels:
    app: {{ template "rabbitmq.name" . }}
    chart: {{ template "rabbitmq.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ include "rabbitmq.name" . }}
      release: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "rabbitmq.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ include "rabbitmq.fullname" . }}
        image: "{{ .Values.rabbitmqImage }}:{{ .Values.rabbitmqTag }}"
        envFrom:
          - configMapRef:
              name: {{ include "rabbitmq.fullname" . }}-env-config-map
        ports:
        - containerPort: {{ .Values.rabbitmq.port1 }}
        - containerPort: {{ .Values.rabbitmq.port2 }}
        volumeMounts:
        - mountPath: {{ .Values.rabbitmq.mountPath }}
          name: {{ include "rabbitmq.fullname" . }}-datarabbit
      volumes:
      - name: {{ include "rabbitmq.fullname" . }}-datarabbit
        persistentVolumeClaim:
          claimName: {{ include "rabbitmq.fullname" . }}-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "rabbitmq.fullname" . }}-pvc
  labels:
    app: {{ template "rabbitmq.name" . }}
    chart: {{ template "rabbitmq.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  storageClassName: {{ .Values.rabbitmq.storageClass }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "rabbitmq.fullname" . }}-pv
  labels:
    app: {{ template "rabbitmq.name" . }}
    chart: {{ template "rabbitmq.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  storageClassName: {{ .Values.rabbitmq.storageClass }}
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /db/rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  labels:
    app: {{ template "rabbitmq.name" . }}
    chart: {{ template "rabbitmq.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - port: {{ .Values.rabbitmq.port1 }}
    targetPort: {{ .Values.rabbitmq.port1 }}
    protocol: TCP
    name: rabbitmq-port-{{ .Values.rabbitmq.port1 }}
  - port: {{ .Values.rabbitmq.port2 }}
    targetPort: {{ .Values.rabbitmq.port2 }}
    protocol: TCP
    name: rabbitmq-port-{{ .Values.rabbitmq.port2 }}
  selector:
    app: {{ include "rabbitmq.name" . }}
    release: {{ .Release.Name }}
  type: {{ .Values.rabbitmq.type }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "rabbitmq.fullname" . }}-from-{{ include "planner.fullname" . }}-{{ include "server.fullname" . }}
  labels:
    app: {{ template "rabbitmq.name" . }}
    chart: {{ template "rabbitmq.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  podSelector:
    matchLabels:
      app: {{ include "rabbitmq.name" . }}
      release: {{ .Release.Name }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ include "planner.name" . }}
          release: {{ .Release.Name }}
    - podSelector:
        matchLabels:
          app: {{ include "server.name" . }}
          release: {{ .Release.Name }}
    ports:
    - port: {{ .Values.rabbitmq.port1 }}
      protocol: TCP
