apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rabbitmq.fullname" . }}-env-config-map
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  RABBITMQ_DEFAULT_USER: {{ .Values.rabbitmq.rabbitmqDefaultUser | quote }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.rabbitmq.rabbitmqDefaultPass | quote }}

