apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rabbitmq.name" . }}-env-config-map
  labels:
    app: {{ template "rabbitmq.name" . }}
    chart: {{ template "rabbitmq.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  RABBITMQ_DEFAULT_USER: {{ .Values.rabbitmq.rabbitmqDefaultUser | quote }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.rabbitmq.rabbitmqDefaultPass | quote }}

