apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rabbitmq.app" . }}-env-config-map
data:
  RABBITMQ_DEFAULT_USER: {{ .Values.rabbitmq.rabbitmqDefaultUser | quote }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.rabbitmq.rabbitmqDefaultPass | quote }}

