---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "toposervice.fullname" . }}
  labels:
    app: {{ template "toposervice.name" . }}
    chart: {{ template "toposervice.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ include "toposervice.name" . }}
      release: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ include "toposervice.name" . }}
        release: {{ .Release.Name }}
        dns-policy: enabled
    spec:
      securityContext:
        runAsUser: {{ .Values.toposervice.user }}
      restartPolicy: Always
      containers:
      - name: {{ include "toposervice.fullname" . }}
        image: "{{ .Values.topoServiceImage }}:{{ .Values.topoServiceTag }}"
        env:
        - name: SPRING_DATA_MONGODB_HOST
          value: {{ include "mongodb.fullname" . }}
        - name: SPRING_DATA_MONGODB_PORT
          value: {{ .Values.mongodb.port1 | quote }}
        - name: SPRING_DATA_MONGODB_DATABASE
          value: {{ .Values.mongodb.database }}
        - name: SPRING_DATA_MONGODB_AUTHENTICATION-DATABASE
          value: {{ .Values.mongodb.authenticationDatabase }}
        - name: SPRING_DATA_MONGODB_USERNAME
          value: {{ .Values.mongodb.rootUsername }}
        - name: SPRING_DATA_MONGODB_PASSWORD
          value: {{ .Values.mongodb.rootPassword }}
        - name: SERVER_PORT
          value: {{ .Values.toposervice.port | quote }}
        ports:
        - containerPort: {{ .Values.toposervice.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "toposervice.fullname" . }}
  labels:
    app: {{ template "toposervice.name" . }}
    chart: {{ template "toposervice.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - port: {{ .Values.toposervice.port }}
    targetPort: {{ .Values.toposervice.port }}
    protocol: TCP
    name: {{ include "toposervice.fullname" . }}-port
  selector:
    app: {{ include "toposervice.name" . }}
    release: {{ .Release.Name }}
  type: {{ .Values.toposervice.type }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "toposervice.fullname" . }}-to-{{ include "mongodb.fullname" . }}
spec:
  podSelector:
    matchLabels:
      app: {{ include "toposervice.name" . }}
      release: {{ .Release.Name }}
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: {{ include "mongodb.name" . }}
          release: {{ .Release.Name }}
    ports:
    - port: {{ .Values.mongodb.port1 }}
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "toposervice.fullname" . }}-from-{{ include "planner.fullname" . }}-ingress
spec:
  podSelector:
    matchLabels:
      app: {{ include "toposervice.name" . }}
      release: {{ .Release.Name }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ include "planner.name" . }}
          release: {{ .Release.Name }}
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: ingress-nginx
      podSelector:
        matchLabels:
          app.kubernetes.io/name: ingress-nginx
    ports:
    - protocol: TCP
      port: {{ .Values.toposervice.port }}
